dndweb/myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('armor/', views.armor_list, name='armor_list'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('profile/', views.userProfile, name='profile'),
    path('profile/update/', views.update_profile, name='profile_update'),  # Correct view function name
    path('characters/', views.character_list, name='characters'),
    path('create_character/', views.create_character, name='create_character'),
    path('races/', views.races_page, name='races_page'),
    path('races/<int:race_id>/', views.race_detail, name='race_detail'),
    path('classes/', views.classes_page, name='classes_page'),
    path('classes/<int:class_id>/', views.class_detail, name='class_detail'),
    path('spells/', views.spells_page, name='spells_page'),
    path('character/<int:character_id>/', views.character_detail, name='character_detail'),
    path('character/<int:character_id>/delete/', views.delete_character, name='character_delete'),
    path('<int:spell_id>/', views.spell_detail, name='spell_detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dndweb/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

dndweb/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from .spell_slots import bard_spell_slots, cleric_spell_slots, druid_spell_slots, paladin_spell_slots, ranger_spell_slots, sorcerer_spell_slots, warlock_spell_slots, wizard_spell_slots, artificer_spell_slots
import os, random
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.models import Group, Permission
from django.conf import settings

class UserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        email = self.normalize_email(email)  # Normalize the email address by lowercasing the domain part of it.
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, email, password, **extra_fields)

class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=200, unique=True, default='username')
    email = models.EmailField(unique=True, null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/default_avatar.jpeg')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="user_set_custom",
        related_query_name="user",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="user_set_custom",
        related_query_name="user",
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

class Rarity(models.Model):
    NONE = "არცერთი"
    COMMON = 'უბრალო'
    UNCOMMON = 'უჩვეულო'
    RARE = 'იშვიათი'
    VERY_RARE = 'ძალიან იშვიათი'
    LEGENDARY = 'ლეგენდარული'
    ARTEFACT = 'არტეფაქტი'
    CHOICES = [
        (NONE, 'არცერთი'),
        (COMMON, 'უბრალო'),
        (UNCOMMON, 'უჩვეულო'),
        (RARE, 'იშვიათი'),
        (VERY_RARE, 'ძალიან იშვიათი'),
        (LEGENDARY, 'ლეგენდარული'),
        (ARTEFACT, 'არტეფაქტი'),
    ]

    name = models.CharField(max_length=20, choices=CHOICES, unique=True)

    def __str__(self):
        return self.name

class Armor(models.Model):
    LIGHT = 'Light'
    MEDIUM = 'Medium'
    HEAVY = 'Heavy'
    NONE = 'None'
    WEIGHT_CLASS_CHOICES = [
        (LIGHT, 'Light'),
        (MEDIUM, 'Medium'),
        (HEAVY, 'Heavy'),
        (NONE, 'None'),
    ]
    name = models.CharField(max_length=50)
    armor_class = models.IntegerField()
    plus_dex_modifier = models.BooleanField(default=False)
    plus_dex_modifier_max_2 = models.BooleanField(default=False)
    strength_requirement = models.IntegerField(null=True, blank=True)
    stealth_disadvantage = models.BooleanField(default=False)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    cost_in_gold = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    rarity = models.ForeignKey(Rarity, on_delete=models.CASCADE)
    weight_class = models.CharField(max_length=10, choices=WEIGHT_CLASS_CHOICES)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Property(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

class Dice(models.Model):
    name = models.CharField(max_length=10)
    sides = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class DamageType(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Weapon(models.Model):
    name = models.CharField(max_length=50)
    cost = models.CharField(max_length=20)
    number_of_dice = models.PositiveIntegerField()
    dice = models.ForeignKey(Dice, on_delete=models.CASCADE, default=1)
    damage_types = models.ManyToManyField(DamageType)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    properties = models.ManyToManyField('Property')
    rarity = models.ForeignKey(Rarity, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    weapon_type = models.CharField(max_length=10, choices=[('simple', 'Simple'), ('martial', 'Martial')], blank=True)
    range_type = models.CharField(max_length=10, choices=[('melee', 'Melee'), ('ranged', 'Ranged')], blank=True)

    def __str__(self):
        return self.name

class Tool(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

class AbilityScore(models.Model):
    ABILITY_SCORE_CHOICES = [
        ('STR', 'Strength'),
        ('DEX', 'Dexterity'),
        ('CON', 'Constitution'),
        ('INT', 'Intelligence'),
        ('WIS', 'Wisdom'),
        ('CHA', 'Charisma'),
    ]
    
    abbreviation = models.CharField(max_length=3, choices=ABILITY_SCORE_CHOICES, unique=True)

    def __str__(self):
        return dict(self.ABILITY_SCORE_CHOICES)[self.abbreviation]

class Skill(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    ability_score = models.ForeignKey(AbilityScore, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class SavingThrow(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class School(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class CastingTime(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Range(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Duration(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Components(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Spell(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()
    school = models.ForeignKey('School', on_delete=models.CASCADE)
    casting_time = models.ForeignKey('CastingTime', on_delete=models.CASCADE)
    range = models.ForeignKey('Range', on_delete=models.CASCADE)
    duration = models.ForeignKey('Duration', on_delete=models.CASCADE)
    components = models.ManyToManyField('Components')
    dice_num = models.PositiveIntegerField(blank=True, null=True)
    dice = models.ForeignKey(Dice, on_delete=models.CASCADE, blank=True, null=True)
    damage_type = models.ForeignKey(DamageType, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()
    at_higher_levels = models.TextField(blank=True) 
    classes_using = models.ManyToManyField('Class', blank=True)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True, default="")

    def __str__(self):
        return self.name

class Feat(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    prerequisites = models.CharField(max_length=200, blank=True)
    benefits = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Race(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    age = models.TextField()
    size = models.TextField()
    speed = models.IntegerField()
    strength = models.IntegerField(default=0)
    dexterity = models.IntegerField(default=0)
    constitution = models.IntegerField(default=0)
    intelligence = models.IntegerField(default=0)
    wisdom = models.IntegerField(default=0)
    charisma = models.IntegerField(default=0)

dndweb/myapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import Character  # Ensure models import doesn't cause a circular dependency

User = get_user_model()

class CustomUserUpdateForm(UserChangeForm):
    email = forms.EmailField(label="იმეილი", required=True)
    avatar = forms.ImageField(label="Avatar", required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super(CustomUserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'
        self.fields['username'].label = "სახელი"
        self.fields['email'].label = "იმეილი"
        del self.fields['password']

class MyUserCreationForm(UserCreationForm):
    username = forms.CharField(label="სახელი", help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    email = forms.EmailField(label="იმეილი")
    password1 = forms.CharField(label="პაროლი", widget=forms.PasswordInput, help_text="Your password can’t be too similar to your other personal information. Your password must contain at least 8 characters. Your password can’t be a commonly used password. Your password can’t be entirely numeric.")
    password2 = forms.CharField(label="გაიმეორე პაროლი", widget=forms.PasswordInput, help_text="Enter the same password as before, for verification.")

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomCharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = [
            'name', 'race', 'subrace', 'dnd_class', 'subclass', 'level', 'alignment', 'background', 
            'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma'
        ]
        
    def __init__(self, *args, **kwargs):
        super(CustomCharacterForm, self).__init__(*args, **kwargs)
        # Set fields as optional
        self.fields['subrace'].required = False
        self.fields['subclass'].required = False
        self.fields['alignment'].required = False
        self.fields['background'].required = False
        self.fields['level'].required = False

dndweb/myapp/templates/base.html
<!DOCTYPE html>
<html lang="geo">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Enigma{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="icon" type="image/x-icon" href="{% static 'image/logo.jpg' %}">
    <link rel="stylesheet" href="{% static 'fonts/mg-glaho-drunk-master/css/mg-glaho-drunk.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ka-lortkipanidze-master/css/ka-lortkipanidze.min.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</body>
</html>

dndweb/myapp/templates/character_list.html
{% extends 'base.html' %}

{% block content %}

{% load static i18n %}

<link rel="stylesheet" href="{% static 'css/character_list.css' %}">

<div class="container">

    <a href="{% url 'create_character' %}">
        <button class="btn btn-primary">{% trans "შექმენი პერსონაჟი" %}</button>
    </a>

    {% if characters %}
        <div class="row">
            {% for character in characters %}
                <div class="col-md-4 col-sm-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">{{ character.name }}</h5>
                            <p class="card-text">{% trans "კლასი" %}: {{ character.dnd_class.name }}</p>
                            <p class="card-text">{% trans "რასა" %}: {{ character.race.name }}</p>
                            <p class="card-text">{% trans "დონე" %}: {{ character.level }}</p>
                            <a href="{% url 'character_detail' character.id %}" class="btn btn-info">{% trans "დეტალები" %}</a>

                            <!-- Delete button form -->
                            <form method="POST" action="{% url 'character_delete' character.id %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger" onclick="return confirm('{% trans "დარწმუნებული ხარ, რომ გინდა, წაშალო პერსონაჟი?" %}');">
                                    {% trans "წაშლა" %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>{% trans "No characters found." %}</p>
    {% endif %}
</div>

{% endblock %}

dndweb/myapp/templates/class_detail.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block title %}
{{ class_obj.name }} Details
{% endblock %}

{% block content %}
<div class="container class-details-container">
    <h1 class="class-details-title">{{ class_obj.name }} Details</h1>
    <div class="class-details-content">
        <p class="class-detail"><span class="class-detail-label">Description:</span> {{ class_obj.description }}</p>
        <p class="class-detail"><span class="class-detail-label">Hit Die:</span> {{ class_obj.hit_die }}</p>
        <p class="class-detail"><span class="class-detail-label">Hit Points at 1st Level:</span> {{ class_obj.hit_points_at_first_level }}</p>
        <p class="class-detail"><span class="class-detail-label">Hit Points at Higher Levels:</span> {{ class_obj.hit_points_at_higher_levels }}</p>
        <p class="class-detail"><span class="class-detail-label">Saving Throw Proficiencies:</span>
            {% for saving_throw in class_obj.saving_throw_proficiencies.all %}
            {{ saving_throw.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Armor Proficiencies:</span>
            {% for armor in class_obj.armor_proficiencies.all %}
            {{ armor.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Weapon Proficiencies:</span>
            {% for weapon in class_obj.weapon_proficiencies.all %}
            {{ weapon.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Tool Proficiencies:</span>
            {% for tool in class_obj.tool_proficiencies.all %}
            {{ tool.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Skill Proficiencies:</span>
            {% for skill in class_obj.skill_proficiencies.all %}
            {{ skill.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Weapon Groups:</span>
            {% for weapon_group in class_obj.weapon_groups.all %}
            {{ weapon_group.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Armor Groups:</span>
            {% for armor_group in class_obj.armor_groups.all %}
            {{ armor_group.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Equipment:</span>
            {% for equipment in class_obj.equipment.all %}
            {{ equipment.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="class-detail"><span class="class-detail-label">Spellcasting Ability:</span> {{ class_obj.spellcasting_ability }}</p>
        <p class="class-detail"><span class="class-detail-label">Traits:</span>
            {% for trait in class_obj.traits.all %}
            {{ trait.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    </div>
</div>
{% endblock %}

dndweb/myapp/templates/classes_page.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block title %}
კლასები
{% endblock %}

{% block content %}
<div class="container classes-container">
    <h1 class="classes-title">კლასები</h1>
    {% for class_obj in classes %}
    <div class="class-item">
        <h2><a href="{% url 'class_detail' class_obj.id %}" class="class-link">{{ class_obj.name }}</a></h2>
        <p>{{ class_obj.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

dndweb/myapp/templates/create_character.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/create_character.css' %}">
{% endblock %}

{% block content %}

<h1>შექმენი პერსონაჟი</h1>

<form method="POST" enctype="multipart/form-data" id="character-form">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="id_name">სახელი:</label>
        <input type="text" class="form-control" id="id_name" name="name" required>
    </div>

    <div class="form-group">
        <label for="id_race">რასა:</label>
        <select class="form-control" id="id_race" name="race" required>
            {% for race in races %}
            <option value="{{ race.id }}">{{ race.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_subrace">ქვერასა:</label>
        <select class="form-control" id="id_subrace" name="subrace">
            {% for subrace in subraces %}
            <option value="{{ subrace.id }}">{{ subrace.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_dnd_class">კლასი:</label>
        <select class="form-control" id="id_dnd_class" name="dnd_class" required>
            {% for dnd_class in classes %}
            <option value="{{ dnd_class.id }}">{{ dnd_class.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_subclass">ქვეკლასი:</label>
        <select class="form-control" id="id_subclass" name="subclass">
            {% for subclass in subclasses %}
            <option value="{{ subclass.id }}">{{ subclass.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_level">დონე:</label>
        <input type="number" class="form-control" id="id_level" name="level" min="1" value="1" required>
    </div>

    <div class="form-group">
        <label for="id_alignment">მორალი:</label>
        <input type="text" class="form-control" id="id_alignment" name="alignment" maxlength="50" required>
    </div>

    <button type="button" class="btn btn-secondary" id="roll-ability-scores">გააგორე მონაცემები</button>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="id_strength">სიძლიერე</label>
                <input type="number" class="form-control ability-score" id="id_strength" name="strength" min="0" required>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_dexterity">მოხერხებულობა</label>
                <input type="number" class="form-control ability-score" id="id_dexterity" name="dexterity" min="0" required>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_constitution">გამძლეობა</label>
                <input type="number" class="form-control ability-score" id="id_constitution" name="constitution" min="0" required>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_intelligence">ინტელექტი</label>
                <input type="number" class="form-control ability-score" id="id_intelligence" name="intelligence" min="0" required>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_wisdom">სიბრძნე</label>
                <input type="number" class="form-control ability-score" id="id_wisdom" name="wisdom" min="0" required>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_charisma">ქარიზმა</label>
                <input type="number" class="form-control ability-score" id="id_charisma" name="charisma" min="0" required>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">შექმენი პერსონაჟი</button>
</form>

<script>
    // Function to roll 4d6 and drop the lowest
    function rollAbilityScore() {
        let rolls = [];
        for (let i = 0; i < 4; i++) {
            rolls.push(Math.floor(Math.random() * 6) + 1);
        }
        rolls.sort((a, b) => a - b);
        rolls.shift(); // Drop the lowest roll
        return rolls.reduce((total, current) => total + current, 0);
    }

    // Function to roll ability scores for the character
    function rollAbilityScores() {
        // Remove any existing rolled scores
        let oldScores = document.querySelectorAll('.ability-score-rolled');
        oldScores.forEach(score => score.remove());

        let abilityInputs = document.querySelectorAll('.ability-score');
        abilityInputs.forEach(input => {
            let rolledScore = rollAbilityScore();
            input.value = rolledScore; // Set input value to rolled score
            input.insertAdjacentHTML('afterend', `<span class="ability-score-rolled">${rolledScore}</span>`); // Display rolled score beside input
        });
    }

    // Roll ability scores when the button is clicked
    document.getElementById('roll-ability-scores').addEventListener('click', rollAbilityScores);
</script>


{% endblock %}

dndweb/myapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block title %}
Index - D&D Webpage
{% endblock %}

{% block content %}
<div class="container">
    <section class="index_section" id="races">
        <h3><a href="{% url 'races_page' %}">რასები</a></h3>
        <ul>
            {% for race in races %}
            <li>
                <a href="{% url 'race_detail' race.id %}" class="link">{{ race.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </section>

    <section class="index_section" id="classes">
        <h3><a href="{% url 'classes_page' %}">კლასები</a></h3>
        <ul>
            {% for class in classes %}
            <li>
                <a href="{% url 'class_detail' class.id %}" class="link">{{ class.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </section>

    <section class="index_section" id="spells">
        <h3><a href="{% url 'spells_page' %}">შელოცვები</a></h3>
    </section>
</div>
{% endblock %}

dndweb/myapp/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <link rel="icon" type="image/x-icon" href="../static/images/favicon_io/logo.jpg">
    <title>DND - enigma</title>
</head>

<body>

    {% include 'navbar.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}


    {% endblock %}

    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

dndweb/myapp/templates/races_page.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block title %}
რასები
{% endblock %}

{% block content %}
<div class="container races-container">
    <h1 class="races-title">რასები</h1>
    {% for race in races %}
    <div class="race-item">
        <h2 class="race-name"><a href="{% url 'race_detail' race.id %}">{{ race.name }}</a></h2>
        <p class="race-description">{{ race.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

dndweb/myapp/templates/spell_detail.html
{% extends 'base.html' %}

{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/spells.css' %}">
{% endblock %}

{% block title %}
{{ spell.name }} Details
{% endblock %}

{% block content %}
<div class="container spell-detail-container">
    <h1 class="spell-detail-title">{{ spell.name }} Details</h1>
    <div class="spell-details">
        <p><strong>School:</strong> {{ spell.school.name }}</p>
        <p><strong>Casting Time:</strong> {{ spell.casting_time.name }}</p>
        <p><strong>Range:</strong> {{ spell.range.name }}</p>
        <p><strong>Duration:</strong> {{ spell.duration.name }}</p>
        <p><strong>Components:</strong>
            {% for component in spell.components.all %}
            {{ component.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>Description:</strong> {{ spell.description }}</p>
    </div>
</div>
{% endblock %}